@Project_HostAddress = http://localhost:5154

### Listagem de produtos
GET http://localhost:5154/api/user/listar

### Cadastro de user
POST http://localhost:5154/api/user/cadastrar
Content-Type: application/json

{
    "nome": "teste8",
    "email": "email@email.com",
    "telefone": 98967912,
    "idade": 28
}

### Buscar Produto 
GET http://localhost:5154/api/user/buscar/NomeTeste

### Deletar
DELETE http://localhost:5154/api/user/remover/NomeTeste

### 
PUT http://localhost:5154/api/user/edit/NomeTeste
Content-Type: application/json

{
    "idade": 20
}

###

POST http://localhost:5154/api/tournament/cadastrar
Content-Type: application/json

{
    "nome": "Torneio 1",
    "users": [],
    "batalha": []
}