@Project_HostAddress = http://localhost:5154

### Listagem de usuários
GET {{Project_HostAddress}}/users/listar

### Cadastro de usuário
POST {{Project_HostAddress}}/users/cadastrar
Content-Type: application/json

{
    "nome": "tesyr",
    "email": "email@email.com",
    "telefone": "98967912",
    "idade": 28
}

### Buscar usuário
GET {{Project_HostAddress}}/users/buscar/teste

### Deletar usuário
DELETE {{Project_HostAddress}}/users/remover/teste

### Editar usuário
PUT {{Project_HostAddress}}/users/edit/teste
Content-Type: application/json

{
    "nome": "teste_editado",
    "email": "email_editado@email.com",
    "telefone": "98967911",
    "idade": 29
}

### Cadastro de torneio
POST {{Project_HostAddress}}/tournament/cadastrar
Content-Type: application/json

{
    "nome": "Torneio 1",
    "descricao": "torneio de verao"
}
### Batalhar
POST {{Project_HostAddress}}/batalhar
Content-Type: application/json

{
    "userId": "dd9db5a5-02ee-4488-8679-cd9b6eee62c6",
    "torneioId": "b7b248fa-8670-469c-a8fd-beb3ce54dcea",
    "jogada": "pedra"
}
