@Project_HostAddress = http://localhost:5154

### Listagem de usuários
GET {{Project_HostAddress}}/users/listar

### Cadastro de usuário
POST {{Project_HostAddress}}/users/cadastrar
Content-Type: application/json

{
    "nome": "teste",
    "email": "email@email.com",
    "telefone": "98967912",
    "idade": 28
}

### Buscar usuário
GET {{Project_HostAddress}}/users/buscar/91809d51-d73b-4548-ab52-349a6d7f4ae6

### Deletar usuário
DELETE {{Project_HostAddress}}/users/remover/5c936435-e1be-4ed4-821f-7d98384bc399

### Editar usuário
PUT {{Project_HostAddress}}/users/edit/1dcb572a-29b0-4cfd-97f5-3739a9ceda74
Content-Type: application/json

{
    "nome": "teste_editado",
    "email": "email_editado@email.com",
    "telefone": "98967911",
    "idade": 29
}

### Cadastro de torneio
POST {{Project_HostAddress}}/tournament/cadastrar
Content-Type: application/json

{
    "nome": "TorneioV",
    "descricao": "torneio de verao",
    "premiacao": 1000.00
}

### Buscar torneio
GET {{Project_HostAddress}}/tournament/buscar/d882f6fc-8837-41e7-9d56-a66940e4af1c

### Deletar torneio
DELETE {{Project_HostAddress}}/tournament/remover/6821b291-adbe-453a-9281-6baf7846b1e3

### Editar torneio
PUT {{Project_HostAddress}}/tournament/edit/d882f6fc-8837-41e7-9d56-a66940e4af1c
Content-Type: application/json

{
    "nome": "TorneioI",
    "descricao": "torneio de inverno",
    "premiacao": 2000.00
}

### Listar torneios
GET {{Project_HostAddress}}/tournament/listar

### Batalhar
POST {{Project_HostAddress}}/batalhar
Content-Type: application/json

{
    "userId": "1dcb572a-29b0-4cfd-97f5-3739a9ceda74",
    "torneioId": "d882f6fc-8837-41e7-9d56-a66940e4af1c",
    "jogada": "pedra"
}

### Listagem das batalhas
GET {{Project_HostAddress}}/batalhas/listar