// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Project.Migrations
{
    [DbContext(typeof(AppDbContext))]
<<<<<<<< HEAD:Project/Project/Migrations/20240519234402_Initial.Designer.cs
    [Migration("20240519234402_Initial")]
    partial class Initial
========
    [Migration("20240520001641_Intial")]
    partial class Intial
>>>>>>>> b9891926f5f086d86869d0deb25e43ea0a7271ab:Project/Project/Migrations/20240520001641_Intial.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("Project.Models.Battle", b =>
                {
                    b.Property<string>("BattleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Jogada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TorneioId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BattleId");

                    b.HasIndex("TorneioId");

                    b.HasIndex("UserId");

                    b.ToTable("Battles");
                });

            modelBuilder.Entity("Project.Models.Torneio", b =>
                {
                    b.Property<string>("TorneioId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Premiacao")
                        .HasColumnType("REAL");

                    b.HasKey("TorneioId");

                    b.ToTable("Torneios");
                });

            modelBuilder.Entity("Project.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("Derrota")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Vitoria")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Project.Models.Battle", b =>
                {
                    b.HasOne("Project.Models.Torneio", "Torneio")
                        .WithMany()
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Torneio");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
